blank_issues_enabled: false
contact_links:
    - name: Minecraft Development for IntelliJ Discord
      url: https://discord.gg/j6UNcfr
      about: Join our Discord server if you just have a question
